const HTTP_STATUS_CODES = Object.freeze({
    SUCCESS: {
      OK: 200,
      CREATED: 201,
      NO_CONTENT: 204,
    },
    CLIENT_ERRORS: {
      BAD_REQUEST: 400,
      UNAUTHORIZED: 401,
      FORBIDDEN: 403,
      NOT_FOUND: 404,
      NOT_ALLOWED: 405,
    },
    SERVER_ERRORS: {
      INTERNAL_SERVER: 500,
    },
  });
  const RESPONSE_STATUS = Object.freeze({
    OK: HTTP_STATUS_CODES.SUCCESS.OK,
    CREATED: HTTP_STATUS_CODES.SUCCESS.CREATED,
    NO_CONTENT: HTTP_STATUS_CODES.SUCCESS.NO_CONTENT,
    BAD_REQUEST: HTTP_STATUS_CODES.CLIENT_ERRORS.BAD_REQUEST,
    UNAUTHORIZED: HTTP_STATUS_CODES.CLIENT_ERRORS.UNAUTHORIZED,
    FORBIDDEN: HTTP_STATUS_CODES.CLIENT_ERRORS.FORBIDDEN,
    NOT_FOUND: HTTP_STATUS_CODES.CLIENT_ERRORS.NOT_FOUND,
    NOT_ALLOWED: HTTP_STATUS_CODES.CLIENT_ERRORS.NOT_ALLOWED,
    INTERNAL_SERVER_ERROR: HTTP_STATUS_CODES.SERVER_ERRORS.INTERNAL_SERVER,
  });

  module.exports = RESPONSE_STATUS